import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@style/globals.css";

const inter = Inter({
      variable: "--font-inter",
      subsets: ["latin"],
      weight: ["400", "500", "600"],
      display: "swap",
});

export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html lang="en">
                  <body
                        className={`${inter.variable} antialiased w-full h-screen flex flex-col justify-between`}
                  >
                        {children}
                  </body>
            </html>
      );
}
